// index.tsx
import Head from "next/head";
import Link from "next/link";
import { Karla } from "next/font/google"
import { IBM_Plex_Mono } from "next/font/google"
import { Input } from "~/components/ui/input"
import Intro from "~/components/Intro"
import AIWriter from "react-aiwriter";
import { useState, useEffect } from "react";
import { useAppContext } from '~/pages/_app';
import axios from "axios";

const sm = IBM_Plex_Mono({
  weight: ['400', '700'],
  subsets: ['latin']
});

const karla = Karla({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin']
});

export default function Home() {
  const [enable, setEnable] = useState(false);
  const [text, setText] = useState("hey! i'm thrifti, your *free* AI financial advisor! i'll learn a little about your spending habits and hopefully save you some cash.");
  const { ctxData, setCtxData } = useAppContext();
  const [umessage, setUMessage] = useState('');
  
  const sendMessage = async () => {
    const response = await axios.post("http://127.0.0.1:5000/chat", {
      messages: [...ctxData.messages, umessage],
    });
    console.log(response.data)
    setCtxData({
      ...ctxData,
      messages: response.data,
    });
  }

  return (
    <>
      <Head>
        <title>thrifti | talk</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"min-h-screen min-w-full bg-gray-100  flex-col content-center items-center justify-center align-center" + karla.className}>
        <div>
            {ctxData.userData.transactions && ctxData.userData.transactions.map((transaction) => (
                <p>{transaction}</p>
            ))
            }
        </div>
        <div>
            {ctxData.messages && ctxData.messages.map((message) => (
                <p>{message}</p>
            ))}
            <input type="text" value={umessage} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUMessage(e.target.value)} />
            <button onClick={() => sendMessage()}>Send!</button>
        </div>
      </main>
    </>
  );
}
