import Head from "next/head";
import Link from "next/link";
import { Karla} from "next/font/google"
import { Input } from "~/components/ui/input"
import Intro from "~/components/Intro"
import AIWriter from "react-aiwriter";

const karla = Karla({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin']
});

export default function Home() {
  return (
    <>
      <Head>
        <title>thrifti</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"min-h-screen min-w-full bg-gray-100 flex content-center items-center justify-center align-center " + karla.className}>
          {/* @ts-ignore */}
          <AIWriter delay={100}>
              <div>
                <p className='text-2xl pb-4 text-emerald-600 w-[400px]'>hey! i'm thrifti, your *free* AI financial advisor! i'll learn a little about your spending habits and hopefully save you some cash.</p>
                <button className="bg-emerald-600">get started -></button>
              </div>
          </AIWriter>
        <Intro/>
      </main>
    </>
  );
}
