// index.tsx
import Head from "next/head";
import Link from "next/link";
import { Karla } from "next/font/google"
import { IBM_Plex_Mono } from "next/font/google"
import { Input } from "~/components/ui/input"
import Intro from "~/components/Intro"
import AIWriter from "react-aiwriter";
import { useState } from "react";

const sm = IBM_Plex_Mono({
  weight: ['400', '700'],
  subsets: ['latin']
});

const karla = Karla({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin']
});

export default function Home() {
  const [enable, setEnable] = useState(false);
  const [text, setText] = useState("hey! i'm thrifti, your *free* AI financial advisor! i'll learn a little about your spending habits and hopefully save you some cash.");
  return (
    <>
      <Head>
        <title>thrifti</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"min-h-screen min-w-full bg-gray-100 flex content-center items-center justify-center align-center " + karla.className}>
          {/* @ts-ignore */}
          <AIWriter delay={100}>
              <div>
                <p className='text-2xl pb-4 mr-8 text-emerald-600 w-[350px]'>{text}</p>
                {!enable && (
                <button onClick={() => setEnable(true)} className={"float-left hover:bg-emerald-700 bg-emerald-600 mt-2 py-2 px-4 rounded-sm text-white v" + sm.className}>get started -></button>
                )}
                </div>
          </AIWriter>
          <Intro enable={enable} textUpdate={setText}/>
      </main>
    </>
  );
}
